function About() {
    return (
        <div className="page-container">
            <h2>About</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Odio ut enim blandit volutpat maecenas volutpat blandit. Ullamcorper a lacus vestibulum sed arcu non odio euismod. Risus quis varius quam quisque id diam vel quam elementum. Sed odio morbi quis commodo odio. Nunc mi ipsum faucibus vitae aliquet nec. Ornare lectus sit amet est placerat in. Libero id faucibus nisl tincidunt eget nullam non. Magna fringilla urna porttitor rhoncus dolor purus. Proin fermentum leo vel orci porta non pulvinar neque laoreet.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Odio ut enim blandit volutpat maecenas volutpat blandit. Ullamcorper a lacus vestibulum sed arcu non odio euismod. Risus quis varius quam quisque id diam vel quam elementum. Sed odio morbi quis commodo odio. Nunc mi ipsum faucibus vitae aliquet nec. Ornare lectus sit amet est placerat in. Libero id faucibus nisl tincidunt eget nullam non. Magna fringilla urna porttitor rhoncus dolor purus. Proin fermentum leo vel orci porta non pulvinar neque laoreet.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Odio ut enim blandit volutpat maecenas volutpat blandit. Ullamcorper a lacus vestibulum sed arcu non odio euismod. Risus quis varius quam quisque id diam vel quam elementum. Sed odio morbi quis commodo odio. Nunc mi ipsum faucibus vitae aliquet nec. Ornare lectus sit amet est placerat in. Libero id faucibus nisl tincidunt eget nullam non. Magna fringilla urna porttitor rhoncus dolor purus. Proin fermentum leo vel orci porta non pulvinar neque laoreet.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Odio ut enim blandit volutpat maecenas volutpat blandit. Ullamcorper a lacus vestibulum sed arcu non odio euismod. Risus quis varius quam quisque id diam vel quam elementum. Sed odio morbi quis commodo odio. Nunc mi ipsum faucibus vitae aliquet nec. Ornare lectus sit amet est placerat in. Libero id faucibus nisl tincidunt eget nullam non. Magna fringilla urna porttitor rhoncus dolor purus. Proin fermentum leo vel orci porta non pulvinar neque laoreet.</p>
        </div>
    )
}

export default About